# Generated by Django 5.1.1 on 2024-11-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecolibrary', '0002_alter_site_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(upload_to='media/sites', verbose_name='Imagen'),
        ),
    ]
