# Generated by Django 5.1.1 on 2024-11-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecolibrary', '0003_alter_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(upload_to='sites/', verbose_name='Imagen'),
        ),
    ]
